// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSOLyg0mfd_X8W1jKPe8C-rmMYpX4m48',
    appId: '1:1063086508546:android:c711989bc6c0ab85c3f51b',
    messagingSenderId: '1063086508546',
    projectId: 'habitsnap-bc5bf',
    storageBucket: 'habitsnap-bc5bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1fUDRGEROlsb5kP2empk7rcaN2qIZRo',
    appId: '1:1063086508546:ios:b2e2b7eeab66bd44c3f51b',
    messagingSenderId: '1063086508546',
    projectId: 'habitsnap-bc5bf',
    storageBucket: 'habitsnap-bc5bf.firebasestorage.app',
    iosClientId: '1063086508546-aea7mvurua1kgdemu34ngrno8hvtck44.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitsnap.RunnerTests',
  );
}
